# Generated by Django 4.0.3 on 2022-03-22 13:49

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prdDetailImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdDetailImg', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='prdDetailThumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdDetailThumb', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('prdTitle', models.CharField(max_length=500)),
                ('prdImgUrl', models.CharField(max_length=500)),
                ('prdImgLink', models.URLField(max_length=500)),
                ('prdOriginPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prdSalePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('prdCate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='manproduct.category')),
                ('prdDetailImgs', models.ManyToManyField(to='manproduct.prddetailimg')),
                ('prdDetailThumbs', models.ManyToManyField(to='manproduct.prddetailthumb')),
            ],
            options={
                'ordering': ['_id', 'update'],
            },
        ),
    ]
